# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"

linter:
  rules:
    # Style
    prefer_single_quotes: true
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    directives_ordering: true

    # Errors
    avoid_print: true
    avoid_unnecessary_containers: true
    avoid_empty_else: true
    avoid_slow_async_io: true
    cancel_subscriptions: true
    close_sinks: true

    # Performance
    use_key_in_widget_constructors: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true

    # Documentation
    public_member_api_docs: false # Can be enabled later

    # Safety
    avoid_web_libraries_in_flutter: true
    no_logic_in_create_state: true

    # Best practices
    always_use_package_imports: true
    avoid_returning_null_for_void: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    require_trailing_commas: true
    sort_child_properties_last: true
    use_super_parameters: true
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
