targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          field_rename: snake

      freezed:
        options:
          map_factory: true
          union_factory: true
