name: countries_app
ddescription: Flutter countries app with Clean Architecture
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3

  # Routing
  go_router: ^16.2.5

  # GraphQL
  graphql_flutter: ^5.1.0

  # Dependency Injection
  get_it: ^8.2.0
  injectable: ^2.5.2

  # Functional Programming & Immutability
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  dartz: ^0.10.1

  # UI
  flutter_hooks: ^0.21.3+1
  cupertino_icons: ^1.0.8

  # Logging
  logger: ^2.6.2

  # Connectivity
  connectivity_plus: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Code Generators
  build_runner: ^2.4.11
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  injectable_generator: ^2.4.1
  riverpod_generator: ^3.0.3

  # Testing
  mocktail: ^1.0.4
  patrol: ^3.19.0

flutter:
  uses-material-design: true
